version: '2'
services:
  emby:
    image: linuxserver/emby
    container_name: emby_normal_scrape
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022 #optional
    volumes:
      - ./var_lib_emby-normalscrape:/config
      - ./transcoding:/transcode
      - /mnt/EmbyMedia_normal_scrape:/mnt/EmbyMedia
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 18098:18098
    restart: unless-stopped
  emby-dmm:
    image: linuxserver/emby
    container_name: emby_VIP_scrape
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022 #optional
    volumes:
      - ./var_lib_emby-vipscrape:/config
      - ./transcoding:/transcode
      - /mnt/EmbyMedia_VIP_scrape:/mnt/EmbyMedia
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 28098:28098
    restart: unless-stopped

